#pragma config(Sensor, dgtl9,  sonarSensor,         sensorSONAR_cm)
#pragma config(Motor,  port2,           leftMotor,     tmotorNormal, openLoop)
#pragma config(Motor,  port3,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Sensor, in6,    lightSensor,         sensorReflection)
#pragma config(Sensor, dgtl11,  button,        sensorDigitalIn)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                   - VEX Smooth Sonar Tracking -                                    *|
|*                                      ROBOTC on VEX 2.0 Cortex                                      *|
|*                                                                                                    *|
|*  This program uses the Ultrasonic sensor to detect objects, and maintain a desired distance from   *|
|*  that object.  However, with standart VEX motors, you may find it difficult to slowly creep up to  *|
|*  the object as the motors will not have enough power to move the robot.                            *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  The Sonar Sensor should be somewhere on the FRONT of the robot, facing FORWARD.             *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]              [Name]              [Type]              [Description]                   *|
|*    Digital 5               sonarSensor         VEX Sonar Sensor    Front mounted, front facing     *|
|*    Motor - Port 2          leftMotor           VEX Motor           Left motor                      *|
|*    Motor - Port 3          rightMotor          VEX Motor           Right motor                     *|
\*-----------------------------------------------------------------------------------------------4246-*/


//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++

int turn(){
	motor[rightMotor]=-127;
	motor[leftMotor]=0;
	wait1Msec(1000);
	motor[rightMotor]=0;
	return 1;
}

task main()
{
  int speed;
  int sonar_value;
  int distance = 15;

  while(true)
  {
  	if(vexRT[Btn8D] == 1 || SensorValue[button] == 0){
  		break;
  	}
  	if(SensorValue(lightSensor) < 700){
    sonar_value = SensorValue(sonarSensor);

    if(sonar_value < 0|| sonar_value >=60)
    {
      speed = 127;
    }
    else if(sonar_value<60&&sonar_value>15)
    {
      speed = 60;
    }
    else if(sonar_value<=distance)
    {
    	 turn();
  	}


    motor[leftMotor]  = speed;
    motor[rightMotor] = speed;

    wait1Msec(100);
  }
  else{
  	motor[leftMotor]  = 0;
    motor[rightMotor] = 0;
  }
  }
}

//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
