#pragma config(Sensor, dgtl1,  rightEncoder,        sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  leftEncoder,         sensorQuadEncoder)
#pragma config(Motor,  port2,           rightMotor,    tmotorNormal, openLoop, reversed)
#pragma config(Motor,  port3,           leftMotor,     tmotorNormal, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*----------------------------------------------------------------------------------------------------*\
|*                                      - Movement by Rotation -                                      *|
|*                                      ROBOTC on VEX 2.0 CORTEX                                      *|
|*                                                                                                    *|
|*  This program uses the Shaft Encoders to move forward for a certain distance.                      *|
|*  There is a two second pause at the beginning of the program.                                      *|
|*                                                                                                    *|
|*                                        ROBOT CONFIGURATION                                         *|
|*    NOTES:                                                                                          *|
|*    1)  Reversing 'rightMotor' (port 2) in the "Motors and Sensors Setup" is needed with the        *|
|*        "Squarebot" mode, but may not be needed for all robot configurations.                       *|
|*    2)  Changing the value of 'distance' will change how far your robot will travel.                *|
|*        !! 360 is equal to one full rotation of the axel !!                                         *|
|*    3)  Whichever encoder is being used for feedback should be cleared just before it starts        *|
|*        counting by using the "SensorValue(encoder) = 0;".  This helps ensure consistancy.          *|
|*                                                                                                    *|
|*    MOTORS & SENSORS:                                                                               *|
|*    [I/O Port]          [Name]              [Type]                [Description]                     *|
|*    Motor   - Port 2    rightMotor          VEX 3-wire module     Right side motor                  *|
|*    Motor   - Port 3    leftMotor           VEX 3-wire module     Left side motor                   *|
|*    Digital - Port 1,2  rightEncoder        VEX Quadrature enc.   Right side encoder                *|
|*    Digital - Port 3,4  leftEncoder         VEX Quadrature enc.   Left side encoder                 *|
\*-----------------------------------------------------------------------------------------------4246-*/

// Hjol er 33.5 cm ummal

//+++++++++++++++++++++++++++++++++++++++++++++| MAIN |+++++++++++++++++++++++++++++++++++++++++++++++
void clearEncoders(){
	SensorValue[rightEncoder] = 0;
  SensorValue[leftEncoder]  = 0;
}
void drive(int dist){
	// 12 cm ummal
	dist*=(360*(100/12));

	clearEncoders();
	// tetta er til ad hann fari rolega af stad svo hann spoli ekki
	for(int i = 0; i>-127;i-=1){
  		motor[rightMotor] = (dist/abs(dist))*i;
    	motor[leftMotor]  = (dist/abs(dist))*i;
    	wait1Msec(10);
  	}
	while(SensorValue[rightEncoder] < dist)
  {
    motor[rightMotor] = (dist/abs(dist))*(-127);
    motor[leftMotor]  = (dist/abs(dist))*(-127);
  }

  motor[rightMotor] = 0;
  motor[leftMotor]  = 0;
}
task main()
{
  /*wait1Msec(2000);

  int distance;
  distance = 360*5;

  SensorValue[rightEncoder] = 0;
  /*SensorValue[leftEncoder]  = 0;

  while(SensorValue[rightEncoder] < distance)
  {
    motor[rightMotor] = -30;
    motor[leftMotor]  = -30;
  }

  motor[rightMotor] = 0;
  motor[leftMotor]  = 0;*/

  // eg veit ekki hvort tetta virkar tvi robotc crashar tegar eg runna med debug streamid opid
  for (int i = 1; i <= 5; i++){
  	writeDebugStream("pp: ",i);
  	drive(i*0.5);
  	drive(-i*0.5);
  }
}
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
